name: CI-BE 🧪

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing

    steps:
      - name: 🧾 Checkout source code
        uses: actions/checkout@v4

      - name: 🛠 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: 📦 Install PHP dependencies
        run: |
          cd sprint5-with-bugs/API
          composer install --no-progress --prefer-dist --no-interaction

      - name: ⚙️ Prepare Laravel
        run: |
          cd sprint5-with-bugs/API
          cp .env.example .env
          php artisan key:generate
          echo "JWT_SECRET=$(openssl rand -hex 32)" >> .env
          php artisan config:clear

      - name: 🧪 Run Laravel Tests
        run: |
          cd sprint5-with-bugs/API
          php artisan test --debug
