name: ci-only

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency: production_environment

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '16'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dev Dependencies
        run: |
          cd sprint5-with-bugs/API
          composer update --no-progress --prefer-dist

      - name: Check PHP extensions
        run: php -m

      - name: Run Laravel Tests
        run: |
          cd sprint5-with-bugs/API
          ./vendor/bin/phpunit
