name: CI-BE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency: production_environment

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '16'
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ':memory:'

    steps:
      - name: 🧾 Checkout source code
        uses: actions/checkout@v4

      - name: 🛠 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: 📦 Install PHP dependencies
        run: |
          cd sprint5/API
          composer install --no-progress --prefer-dist --no-interaction
          composer require --dev brianium/paratest:^7.0

      - name: ⚙️ Prepare Laravel for testing
        run: |
          cd sprint5/API
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: 🧪 Run Laravel Tests in parallel
        run: |
          cd sprint5/API
          php artisan test --parallel
